### PR TITLE
Iop xxxx address

### PR DESCRIPTION
**Pull request by kokosabu**
work in progress

### CODE REVIEW

**Review by sdswoops824 — COMMENTED** [review]
May be we can use ROS_INFO_THROTTLE instead of ROS_INFO?

**Comment by kokosabu** [comment]
@sdswoops824 
We want to solve the issue we call skipping. I don't think THROTTLE can be used until the issue is resolved. I think the timing is pretty severe for the skip issue. Sometimes it doesn't occur in the same place and sometimes it does.
Also, this is basically the code I intend to throw away once the skip issue is resolved. Please let me know if there is any code you would like to keep.

**Comment by sdswoops824** [comment]
> @sdswoops824 We want to solve the issue we call skipping. I don't think THROTTLE can be used until the issue is resolved. I think the timing is pretty severe for the skip issue. Sometimes it doesn't occur in the same place and sometimes it does. Also, this is basically the code I intend to throw away once the skip issue is resolved. Please let me know if there is any code you would like to keep.

Thank you Miura san. Yes, I understand that this is for the skip issue. I just thought THROTTLE will let us reduce the frequency of logs to make it a little more manageable. But its up to you. :bow:

**Review by sdswoops824 — APPROVED** [review]

**Comment by kokosabu** [comment]
#96 is implementing measures that are considered to be effective at this time. However, since we cannot say with confidence that this is a 100% solution, we will leave some of the log output used during the investigation.

**Pull request merged**
